# Generated by Django 5.2.5 on 2026-08-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0019_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount_eur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Euros'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='bank_fee_eur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Comisión euros (€)'),
        ),
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('BS', 'Bolívares'), ('USD', 'Dólares'), ('EUR', 'Euros')], default='BS', max_length=3, verbose_name='Moneda'),
        ),
    ]
