# Generated by Django 5.2.5 on 2026-08-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0020_transaction_amount_eur_transaction_bank_fee_eur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='bank_fee_real_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Comisión dólares ($)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='real_dollars',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Dólares'),
        ),
    ]
