# Generated by Django 5.2.5 on 2026-08-26 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0021_alter_transaction_bank_fee_real_usd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='account',
            name='bank_code',
        ),
        migrations.RemoveField(
            model_name='account',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='holder',
        ),
        migrations.RemoveField(
            model_name='account',
            name='rif',
        ),
    ]
