# Generated by Django 5.2.5 on 2026-08-28 13:29

import django.db.models.deletion
import organizations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0022_remove_account_account_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to=organizations.models.transaction_photo_path, verbose_name='Imagen')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='Nombre original')),
                ('size_bytes', models.PositiveIntegerField(default=0, verbose_name='Tamaño (bytes)')),
                ('width', models.PositiveIntegerField(default=0, verbose_name='Ancho')),
                ('height', models.PositiveIntegerField(default=0, verbose_name='Alto')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='organizations.transaction', verbose_name='Transacción')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_photos', to=settings.AUTH_USER_MODEL, verbose_name='Subida por')),
            ],
            options={
                'verbose_name': 'Foto de transacción',
                'verbose_name_plural': 'Fotos de transacción',
                'ordering': ['position', 'id'],
                'indexes': [models.Index(fields=['transaction', 'position'], name='organizatio_transac_5a35aa_idx')],
            },
        ),
    ]
